site_name: CSCI 3600 – Internet Programming
site_description: Augusta University • Course notes and labs
repo_url: https://github.com/rahaeimehr/internet-programming

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - toc.follow
extra_css:
  - assets/raha.css

plugins:
  - search
  - print-site:
      #add_to_navigation: true        # optional: shows "Print / PDF" in navbar
      print_page_title: "Print / PDF"  

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Modules:
      - "Module 01: Intro to the Web & HTML": module-01-intro-html/index.md
      - "Module 02: Intro to CSS": module-02-intro-css/index.md
      - "Module 03: HTML Advanced & Media Embedding": module-03-advanced-html/index.md
      - "Module 04: CSS Layouts and Positioning": module-04-css-layouts-and-positioning/index.md
      - "Module 05: Responsive Design & Media Queries": module-05-responsive-design/index.md
      - "Module 06: JavaScript Fundamentals": module-06-javascript_fundamentals/index.md
      - "Module 07: JavaScript & the Browser": module-07-javascript_browser/index.md
      - "Module 08: Introduction to Node.js": module-08-introduction_to_nodejs/index.md
      - "Module 09: Web Servers with Node.js and Express": module-09-webserver_express/index.md
      - "Module 10: Templating and Forms with Express": module-10-templating_forms/index.md
      - "Module 11: Working with Data": module-11-working-with-data/index.md
      - "Module 12: State Management and Authentication": module-12-state-management-and-authentication/index.md

      
